import type { Patient } from '../models/Patient';

export interface PatientRepository {
  /**
   * Retrieves a list of all patients.
   */
  getPatients(): Promise<Patient[]>;

  /**
   * Retrieves a single patient by ID.
   * @param id The patient ID.
   */
  getPatientById(id: string): Promise<Patient | null>;

  /**
   * Creates a new patient.
   * @param patient The patient data (without ID or autogenerated fields).
   */
  createPatient(patient: Omit<Patient, 'id' | 'createdAt' | 'updatedAt'>): Promise<Patient>;

  /**
   * Updates an existing patient.
   * @param id The patient ID.
   * @param patient The fields to update.
   */
  updatePatient(id: string, patient: Partial<Patient>): Promise<Patient>;

  /**
   * Deletes a patient.
   * @param id The patient ID.
   */
  deletePatient(id: string): Promise<void>;
}
